export const LOADING = "LOADING";
export const FULL_PAGE_LOADING = "FULL_PAGE_LOADING";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";
export const VERIFY_USER = "VERIFY_USER";

export const SET_TIMERS = "SET_TIMERS";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_TIMER_SOUNDS = "SET_TIMER_SOUNDS";

export const SET_TIMER_INTERVALS = "SET_TIMER_INTERVALS";
export const ADD_TIMER_INTERVAL = "ADD_TIMER_INTERVAL";
export const UPDATE_TIMER_INTERVAL = "UPDATE_TIMER_INTERVAL";
export const REMOVE_TIMER_INTERVALS = "REMOVE_TIMER_INTERVALS";
